{% import '../Version.njk' as sync_version -%}

[toolchain]
channel = "{{ sync_version.rust_toolchain }}"

[tools]
cargo-make = "{{ sync_version.cargo_make }}"
cargo-tarpaulin = "{{ sync_version.cargo_tarpaulin }}"
cargo-release = "{{ sync_version.cargo_release }}"
