# This workflow validates the formatting of Rust code, 
# make sure Rust test are passing and run some validation on the Rust documentation.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

name: Validate rust code.

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rust_ci:
    name: Rust CI
    
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout Repository âœ…
        uses: actions/checkout@v4
 
      - name: ğŸ› ï¸ Download Rust Tools ğŸ› ï¸
        uses: microsoft/mu_devops/.github/actions/rust-tool-cache@main
      
      - name: Run cargo-fmt
        run: cargo fmt --all --check
        env:
          RUSTC_BOOTSTRAP: 1

      - name: ğŸ“ Run cargo-clippy ğŸ“
        if: success() || failure()
        run: cargo clippy --all-targets --all-features -- -D warnings
        env:
          RUSTC_BOOTSTRAP: 1
          
      - name: ğŸ§ª Run Tests ğŸ§ª
        if: success() || failure()
        run: cargo make coverage
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Test Documentation
        if: success() || failure()
        run: cargo test --doc
        env:
          RUSTC_BOOTSTRAP: 1

      - name: Build documentation
        if: success() || failure()
        run: cargo make doc
        env:
          RUSTC_BOOTSTRAP: 1
